In [8]:
import pandas as pd

In [10]:
#file source
#pd.read_parquet("./tmp4/RDAC1901.parquet").head(100).to_csv("RDAC1901.csv",index=False)

df = pd.read_csv('sample/RDAC1901.csv')
df.head()

,UF_ZI,ANO_CMPT,MES_CMPT,ESPEC,CGC_HOSP,N_AIH,IDENT,CEP,MUNIC_RES,NASC,...,DIAGSEC9,TPDISEC1,TPDISEC2,TPDISEC3,TPDISEC4,TPDISEC5,TPDISEC6,TPDISEC7,TPDISEC8,TPDISEC9
0,120000,2019,1,2,4034526003320,1219100035901,1,69930000,120070,19900415,...,,0,0,0,0,0,0,0,0,0
1,120000,2019,1,2,4034526003320,1219100035912,1,69930000,120070,19910613,...,,0,0,0,0,0,0,0,0,0
2,120000,2019,1,2,4034526003320,1219100035923,1,69930000,120070,19950825,...,,0,0,0,0,0,0,0,0,0
3,120000,2019,1,2,4034526003320,1219100035934,1,69930000,120070,19971008,...,,0,0,0,0,0,0,0,0,0
4,120000,2019,1,2,4034526003320,1219100035945,1,69930000,120070,19990712,...,,0,0,0,0,0,0,0,0,0

In [11]:
df.info(max_cols=113)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 113 columns):
 #    Column      Non-Null Count  Dtype
---   ------      --------------  -----
 0    UF_ZI       100 non-null    int64
 1    ANO_CMPT    100 non-null    int64
 2    MES_CMPT    100 non-null    int64
 3    ESPEC       100 non-null    int64
 4    CGC_HOSP    100 non-null    int64
 5    N_AIH       100 non-null    int64
 6    IDENT       100 non-null    int64
 7    CEP         100 non-null    int64
 8    MUNIC_RES   100 non-null    int64
 9    NASC        100 non-null    int64
 10   SEXO        100 non-null    int64
 11   UTI_MES_IN  100 non-null    int64
 12   UTI_MES_AN  100 non-null    int64
 13   UTI_MES_AL  100 non-null    int64
 14   UTI_MES_TO  100 non-null    int64
 15   MARCA_UTI   100 non-null    int64
 16   UTI_INT_IN  100 non-null    int64
 17   UTI_INT_AN  100 non-null    int64
 18   UTI_INT_AL  100 non-null    int64
 19   UTI_INT_TO  100 non-null    int64
 20   DIAR_ACOM   100 non-null    int64
 21   QT_DIARIAS  100 non-null    int64
 22   PROC_SOLIC  100 non-null    int64
 23   PROC_REA    100 non-null    int64
 24   VAL_SH      100 non-null    float64
 25   VAL_SP      100 non-null    float64
 26   VAL_SADT    100 non-null    float64
 27   VAL_RN      100 non-null    float64
 28   VAL_ACOMP   100 non-null    float64
 29   VAL_ORTP    100 non-null    float64
 30   VAL_SANGUE  100 non-null    float64
 31   VAL_SADTSR  100 non-null    float64
 32   VAL_TRANSP  100 non-null    float64
 33   VAL_OBSANG  100 non-null    float64
 34   VAL_PED1AC  100 non-null    float64
 35   VAL_TOT     100 non-null    float64
 36   VAL_UTI     100 non-null    float64
 37   US_TOT      100 non-null    float64
 38   DT_INTER    100 non-null    int64
 39   DT_SAIDA    100 non-null    int64
 40   DIAG_PRINC  100 non-null    object
 41   DIAG_SECUN  100 non-null    int64
 42   COBRANCA    100 non-null    int64
 43   NATUREZA    100 non-null    int64
 44   NAT_JUR     100 non-null    int64
 45   GESTAO      100 non-null    int64
 46   RUBRICA     100 non-null    int64
 47   IND_VDRL    100 non-null    int64
 48   MUNIC_MOV   100 non-null    int64
 49   COD_IDADE   100 non-null    int64
 50   IDADE       100 non-null    int64
 51   DIAS_PERM   100 non-null    int64
 52   MORTE       100 non-null    int64
 53   NACIONAL    100 non-null    int64
 54   NUM_PROC    100 non-null    object
 55   CAR_INT     100 non-null    int64
 56   TOT_PT_SP   100 non-null    int64
 57   CPF_AUT     100 non-null    object
 58   HOMONIMO    100 non-null    int64
 59   NUM_FILHOS  100 non-null    int64
 60   INSTRU      100 non-null    int64
 61   CID_NOTIF   100 non-null    object
 62   CONTRACEP1  100 non-null    int64
 63   CONTRACEP2  100 non-null    int64
 64   GESTRISCO   100 non-null    int64
 65   INSC_PN     100 non-null    int64
 66   SEQ_AIH5    100 non-null    int64
 67   CBOR        100 non-null    int64
 68   CNAER       100 non-null    int64
 69   VINCPREV    100 non-null    int64
 70   GESTOR_COD  100 non-null    int64
 71   GESTOR_TP   100 non-null    int64
 72   GESTOR_CPF  100 non-null    int64
 73   GESTOR_DT   100 non-null    object
 74   CNES        100 non-null    int64
 75   CNPJ_MANT   100 non-null    int64
 76   INFEHOSP    100 non-null    object
 77   CID_ASSO    100 non-null    int64
 78   CID_MORTE   100 non-null    int64
 79   COMPLEX     100 non-null    int64
 80   FINANC      100 non-null    int64
 81   FAEC_TP     100 non-null    object
 82   REGCT       100 non-null    int64
 83   RACA_COR    100 non-null    int64
 84   ETNIA       100 non-null    int64
 85   SEQUENCIA   100 non-null    int64
 86   REMESSA     100 non-null    object
 87   AUD_JUST    100 non-null    object
 88   SIS_JUST    100 non-null    object
 89   VAL_SH_FED  100 non-null    float64
 90   VAL_SP_FED  100 non-null    float64
 91   VAL_SH_GES  100 non-null    float64
 92   VAL_SP_GES  100 non-null    float64
 93   VAL_UCI     100 non-null    float64
 94   MARCA_UCI   100 non-null    int64
 95   DIAGSEC1    100 non-null    object
 96   DIAGSEC2    100 non-null    object
 97   DIAGSEC3    100 non-null    object
 98   DIAGSEC4    100 non-null    object
 99   DIAGSEC5    100 non-null    object
 100  DIAGSEC6    100 non-null    object
 101  DIAGSEC7    100 non-null    object
 102  DIAGSEC8    100 non-null    object
 103  DIAGSEC9    100 non-null    object
 104  TPDISEC1    100 non-null    int64
 105  TPDISEC2    100 non-null    int64
 106  TPDISEC3    100 non-null    int64
 107  TPDISEC4    100 non-null    int64
 108  TPDISEC5    100 non-null    int64
 109  TPDISEC6    100 non-null    int64
 110  TPDISEC7    100 non-null    int64
 111  TPDISEC8    100 non-null    int64
 112  TPDISEC9    100 non-null    int64
dtypes: float64(19), int64(75), object(19)
memory usage: 88.4+ KB

In [19]:
with pd.option_context('display.max_rows', 10, 'display.max_columns', None): 
    display(df.describe())

,UF_ZI,ANO_CMPT,MES_CMPT,ESPEC,CGC_HOSP,N_AIH,IDENT,CEP,MUNIC_RES,NASC,SEXO,UTI_MES_IN,UTI_MES_AN,UTI_MES_AL,UTI_MES_TO,MARCA_UTI,UTI_INT_IN,UTI_INT_AN,UTI_INT_AL,UTI_INT_TO,DIAR_ACOM,QT_DIARIAS,PROC_SOLIC,PROC_REA,VAL_SH,VAL_SP,VAL_SADT,VAL_RN,VAL_ACOMP,VAL_ORTP,VAL_SANGUE,VAL_SADTSR,VAL_TRANSP,VAL_OBSANG,VAL_PED1AC,VAL_TOT,VAL_UTI,US_TOT,DT_INTER,DT_SAIDA,DIAG_SECUN,COBRANCA,NATUREZA,NAT_JUR,GESTAO,RUBRICA,IND_VDRL,MUNIC_MOV,COD_IDADE,IDADE,DIAS_PERM,MORTE,NACIONAL,CAR_INT,TOT_PT_SP,HOMONIMO,NUM_FILHOS,INSTRU,CONTRACEP1,CONTRACEP2,GESTRISCO,INSC_PN,SEQ_AIH5,CBOR,CNAER,VINCPREV,GESTOR_COD,GESTOR_TP,GESTOR_CPF,CNES,CNPJ_MANT,CID_ASSO,CID_MORTE,COMPLEX,FINANC,REGCT,RACA_COR,ETNIA,SEQUENCIA,VAL_SH_FED,VAL_SP_FED,VAL_SH_GES,VAL_SP_GES,VAL_UCI,MARCA_UCI,TPDISEC1,TPDISEC2,TPDISEC3,TPDISEC4,TPDISEC5,TPDISEC6,TPDISEC7,TPDISEC8,TPDISEC9
count,100.0,100.0,100.0,100.000000,1.000000e+02,1.000000e+02,100.0,1.000000e+02,100.000000,1.000000e+02,100.000000,100.0,100.0,100.0,100.000000,100.000000,100.0,100.0,100.0,100.0,100.000000,100.000000,1.000000e+02,1.000000e+02,100.000000,100.000000,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.000000,100.000000,100.000000,1.000000e+02,1.000000e+02,100.0,100.000000,100.0,100.000000,100.0,100.0,100.000000,100.00000,100.00000,100.000000,100.000000,100.000000,100.0,100.000000,100.0,100.0,100.000000,100.00000,100.000000,100.000000,100.0,1.000000e+02,100.0,100.0,100.0,100.0,100.0,100.00000,1.000000e+02,1.000000e+02,1.000000e+02,100.0,100.0,100.0,100.0,100.0,100.00000,100.00,100.000000,100.0,100.0,100.0,100.0,100.0,100.0,100.000000,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
mean,120000.0,2019.0,1.0,3.280000,2.912899e+12,1.218670e+12,1.0,6.992725e+07,120549.740000,1.989235e+07,2.420000,0.0,0.0,0.0,0.680000,3.870000,0.0,0.0,0.0,0.0,2.170000,3.300000,3.226908e+08,3.226908e+08,635.995000,147.824400,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,783.819400,325.529600,210.133900,2.018618e+07,2.018636e+07,0.0,31.230000,0.0,1975.320000,2.0,0.0,0.320000,120049.50000,3.83000,29.160000,3.870000,0.040000,10.0,1.930000,0.0,0.0,0.060000,0.05000,0.200000,0.160000,1.0,1.212476e+10,0.0,0.0,0.0,0.0,0.0,0.08000,2.823178e+09,2.001157e+06,2.912899e+12,0.0,0.0,2.0,6.0,0.0,33.72000,1.11,4075.070000,0.0,0.0,0.0,0.0,0.0,0.0,0.050000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
std,0.0,0.0,0.0,1.826184,1.643275e+12,4.973029e+08,0.0,2.556080e+04,2195.132156,2.153146e+05,0.912096,0.0,0.0,0.0,3.930919,16.966786,0.0,0.0,0.0,0.0,2.609443,2.687419,4.001666e+07,4.001666e+07,1875.508132,274.560552,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2137.748813,1881.809363,573.123464,4.458866e+03,4.432608e+03,0.0,22.600552,0.0,1395.226689,0.0,0.0,0.468826,9.36089,0.53286,21.112359,4.191514,0.196946,0.0,0.256432,0.0,0.0,0.422116,0.35887,1.407053,1.125642,0.0,4.816535e+10,0.0,0.0,0.0,0.0,0.0,0.27266,9.622094e+09,6.670607e+02,1.643275e+12,0.0,0.0,0.0,0.0,0.0,45.00821,11.10,213.823219,0.0,0.0,0.0,0.0,0.0,0.0,0.297294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,120000.0,2019.0,1.0,1.000000,5.294430e+11,1.218100e+12,1.0,6.985000e+07,120001.000000,1.929122e+07,1.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,3.010600e+08,3.010600e+08,33.340000,10.880000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,44.220000,0.000000,11.850000,2.018092e+07,2.018093e+07,0.0,12.000000,0.0,1023.000000,2.0,0.0,0.000000,120040.00000,2.00000,0.000000,1.000000,0.000000,10.0,1.000000,0.0,0.0,0.000000,0.00000,0.000000,0.000000,1.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.00000,0.000000e+00,2.000121e+06,5.294430e+11,0.0,0.0,2.0,6.0,0.0,1.00000,0.00,3316.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,120000.0,2019.0,1.0,2.000000,5.294430e+11,1.218101e+12,1.0,6.990097e+07,120040.000000,1.982079e+07,1.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,1.000000,3.030526e+08,3.030526e+08,214.880000,30.680000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,242.680000,0.000000,65.060000,2.018122e+07,2.018122e+07,0.0,12.000000,0.0,1023.000000,2.0,0.0,0.000000,120040.00000,4.00000,16.000000,1.750000,0.000000,10.0,2.000000,0.0,0.0,0.000000,0.00000,0.000000,0.000000,1.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.00000,0.000000e+00,2.000865e+06,5.294430e+11,0.0,0.0,2.0,6.0,0.0,3.00000,0.00,3961.750000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,120000.0,2019.0,1.0,3.000000,4.034526e+12,1.219100e+12,1.0,6.994000e+07,120050.000000,1.994060e+07,3.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,1.500000,2.000000,3.031451e+08,3.031451e+08,277.020000,50.320000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,443.400000,0.000000,118.870000,2.019010e+07,2.019011e+07,0.0,12.000000,0.0,1023.000000,2.0,0.0,0.000000,120050.00000,4.00000,24.500000,2.000000,0.000000,10.0,2.000000,0.0,0.0,0.000000,0.00000,0.000000,0.000000,1.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.00000,0.000000e+00,2.000865e+06,4.034526e+12,0.0,0.0,2.0,6.0,0.0,3.00000,0.00,4105.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75%,120000.0,2019.0,1.0,3.000000,4.034526e+12,1.219100e+12,1.0,6.994000e+07,120050.000000,2.002062e+07,3.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,3.000000,4.250000,3.100100e+08,3.100100e+08,432.555000,175.800000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,563.562500,0.000000,151.085000,2.019011e+07,2.019012e+07,0.0,61.000000,0.0,3999.000000,2.0,0.0,1.000000,120050.00000,4.00000,36.000000,5.000000,0.000000,10.0,2.000000,0.0,0.0,0.000000,0.00000,0.000000,0.000000,1.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.00000,0.000000e+00,2.002078e+06,4.034526e+12,0.0,0.0,2.0,6.0,0.0,99.00000,0.00,4217.250000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
max,120000.0,2019.0,1.0,7.000000,4.034526e+12,1.219100e+12,1.0,6.997500e+07,130070.000000,2.018123e+07,3.000000,0.0,0.0,0.0,34.000000,81.000000,0.0,0.0,0.0,0.0,12.000000,12.000000,4.110100e+08,4.110100e+08,15529.670000,2339.050000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17868.720000,16276.480000,4790.540000,2.019013e+07,2.019013e+07,0.0,61.000000,0.0,3999.000000,2.0,0.0,1.000000,120070.00000,4.00000,89.000000,33.000000,1.000000,10.0,2.000000,0.0,0.0,3.000000,3.00000,10.000000,8.000000,1.0,2.018121e+11,0.0,0.0,0.0,0.0,0.0,1.00000,3.528972e+10,2.002078e+06,4.034526e+12,0.0,0.0,2.0,6.0,0.0,99.00000,111.00,4347.000000,0.0,0.0,0.0,0.0,0.0,0.0,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0